client:
  hosts: {{ es_hosts }}
  port: 9200

  url_prefix:

  use_ssl: False
  certificate:
  client_cert:
  client_key:
  ssl_no_validate: False

  http_auth:

  timeout: {{ timoeut }}
  master_only: false

logging:
  loglevel: INFO
  logfile:
  logformat: default
  blacklist: ['elasticsearch', 'urllib3']
